# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc9b508e2da89e4c4df0e128b0b2379f6588b99f6be15777ba45980bcd9f6a57f93a41428a02fd6a0f4e692c4c48b0cbbdcc13df4ba77d467acb61d666ca9cd5

test:
  secret_key_base: e758351af99cbe3f951445340a8bc8cbfa8af2fa0fd70ebeffa1ed3e992b94c94256432e6e449502f1946009cf6b8781c4692d24d94f55ab893934866f059216

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
